{
 "title": "qh3server",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "h3 requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "rawSql": "SELECT \"time\" AS \"time\", COUNT(count_val), device_name FROM gsdk_stats.stats_count WHERE (count = 'recv_cb' AND legend = 'create_conn_io') GROUP BY \"time\", count_val, device_name ORDER BY \"time\" "
    },
    {
     "rawSql": "SELECT \"time\" AS \"time\", COUNT(count_val) AS \"error\", device_name FROM gsdk_stats.stats_count WHERE (count = 'recv_cb' AND epic = 'error') GROUP BY \"time\", count_val, device_name ORDER BY \"time\" "
    },
    {
     "rawSql": "SELECT \"time\" AS \"time\", COUNT(count_val), device_name FROM gsdk_stats.stats_count WHERE (count = 'parse' AND epic = 'error') GROUP BY \"time\", count_val, device_name ORDER BY \"time\" "
    }
   ]
  },
  {
   "title": "ram usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "rawSql": "SELECT \"time\" AS \"time\", MAX(total_ram) AS \"ram\", device_name FROM gsdk_stats.stats_count WHERE (count = 'recv_cb' AND legend = 'create_conn_io') GROUP BY \"time\", count_val, device_name ORDER BY \"time\" "
    }
   ]
  },
  {
   "title": "h3 user_get",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "rawSql": "SELECT \"time\" AS \"time\", COUNT(count_val), device_name, story as server FROM gsdk_stats.stats_count WHERE (count = 'parse' AND epic = 'hit' AND legend = '/user_get') GROUP BY \"time\", count_val, device_name, story ORDER BY \"time\" "
    }
   ]
  },
  {
   "title": "h3 user_token_mismatch",
   "type": "timeseries",
   "description": "if a user try to use a get or post request with expired token.",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \"time\" AS \"time\", COUNT(count_val), device_name, session AS \"t_session\", legend AS \"api\", story as server FROM gsdk_stats.stats_count WHERE (count = 'validte_token' AND message = 'user.token_check' AND legend = '/user_details' AND epic <> session) GROUP BY \"time\", count_val, device_name, session, legend, story ORDER BY \"time\" "
    }
   ]
  },
  {
   "title": "h3 rx",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 7, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT \"time\" AS \"time\", SUM(count_val), device_name, story AS \"server\" FROM gsdk_stats.stats_count WHERE (count = 'recv_cb' AND epic = 'rx') GROUP BY \"time\", count_val, device_name, story ORDER BY \"time\" "
    }
   ]
  },
  {
   "title": "h3 tx",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "rawSql": "SELECT \"time\" AS \"time\", SUM(count_val) AS \"recv_cb\", device_name, story as server FROM gsdk_stats.stats_count WHERE (count='recv_cb' AND epic='tx') GROUP BY \"time\", count_val, device_name, story ORDER BY \"time\" LIMIT 200 "
    },
    {
     "rawSql": "SELECT \"time\" AS \"time\", SUM(count_val) AS \"flush_egress\", device_name FROM gsdk_stats.stats_count WHERE (count = 'flush_egress' AND epic = 'tx') GROUP BY \"time\", count_val, device_name ORDER BY \"time\" "
    }
   ]
  },
  {
   "title": "h3 user_detail",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "rawSql": "SELECT \"time\" AS \"time\", COUNT(count_val), device_name, story as server FROM gsdk_stats.stats_count WHERE (count = 'parse' AND legend = '/user_details') GROUP BY \"time\", count_val, device_name, story ORDER BY \"time\" "
    }
   ]
  }
 ]
}