using System;
using UnityEngine;
using UnityEngine.UI;

public class Qsocket_Test : MonoBehaviour
{
    qunitysdk.qsocket qsocket = null;
    public Button send_btn;
    public Button close_btn;
    public TMPro.TextMeshProUGUI response_text;
    public string server_ip = "127.0.0.1";
    private string pid = "";

    private void Start() {
        qsocket = new qunitysdk.qsocket();
        // NOTE :- this pid must be unique and it must be generated by a centralised system.
        // Here we are using the guid hash to generate a unique id for demo purpose.
        pid = qsocket.guid_crc.ToString("x");
        LogMessage("guid " + qsocket.guid_crc);
    }

    public void On_Btn_QSocketConnect() {
        qsocket.connect(server_ip, "4000", IntPtr.Zero);
        qsocket.OnConnect = onconnect;
        qsocket.OnMessage = onmessage;
        qsocket.OnReleaseConnection = onreleaseconnection;
        qsocket.OnClose = onclose;
    }

    public void On_Btn_QSocketSend() {
        qsocket.sendMessage("Hello !!!", true);
    }

    public void On_Btn_SocketClose() {
        qsocket.close();
    }

    public void LogMessage(string msg) {
        Debug.Log($"[{pid}] - {msg}");
    }

    protected void onconnect( qunitysdk.qsocket qs ) {
        LogMessage("qsocket connected");
        msg_room_match_request msg_room_config_packet = new msg_room_match_request(pid);
        msg_room_config_packet.room_config = new msg_room_config();
        string payload = JsonUtility.ToJson(msg_room_config_packet);
        LogMessage($"sending : {payload}");
        qs.sendMessage(payload, true);
        send_btn.interactable = true;
        close_btn.interactable = true;
    }

    protected void onmessage( qunitysdk.qsocket qs, ulong recv_len, string msg ) {
        response_text.text = msg;
        response_text.gameObject.SetActive(true);
        LogMessage($"received : {msg}");
    }

    protected void onreleaseconnection( qunitysdk.qsocket qs ) {
        LogMessage("qsocket release connection");
    }

    protected void onclose( qunitysdk.qsocket qs ) {
        LogMessage("qsocket close connection");
        send_btn.interactable = false;
        close_btn.interactable = false;
    }
}
