//
//  Copyright 2024 homenet25
//  gameclient.cpp
//  networkclient
//
//  Created by Arun A on 15/10/23.
//

#include "gameclient.hpp"

#include "../../networkcommon/source/message.hpp"
#include "../../networkcommon/source/roommessage.hpp"

gameclient::~gameclient() {}

void gameclient::onconnect(conn_io_client* qconnection) {
	if (shutdown_client) {
		test_send_shutdown_event();
		return;
	}
	Document doc;
	msg_room_match_request* msg = dynamic_cast<msg_room_match_request*>(msg_room_match_request::create());
	// NOTE :- this pid must be unique and it must be generated by a centralised system.
	// Here we are using the cid hash to generate a unique id for demo purpose.
	msg->pid.format("%lx", qconnection->cid_hash_val);
	qstring msg_room_config_packet;
	msg->serialize(doc, doc.GetAllocator());
	essentials::get_json_string(doc, msg_room_config_packet);
	debug_print(LOG_LEVEL_2, __LOGTAG__, "room config --> %s", msg_room_config_packet.c_str());
	send_message(msg_room_config_packet, true);
	GX_DELETE(msg);
}

void gameclient::test_send_shutdown_event() {
	Document doc;
	msg_room_server_shutdown* msg = dynamic_cast<msg_room_server_shutdown*>(msg_room_server_shutdown::create());
	qstring msg_room_server_shutdown_packet;
	msg->serialize(doc, doc.GetAllocator());
	essentials::get_json_string(doc, msg_room_server_shutdown_packet);
	debug_print(LOG_LEVEL_2, __LOGTAG__, "room shutdown --> %s", msg_room_server_shutdown_packet.c_str());
	send_message(msg_room_server_shutdown_packet, true);
	GX_DELETE(msg);
}
