//
//  Copyright 2024 homenet25
//  gclient.cpp
//  qgfist
//
//  Created by Arun A on 17/09/2024.
//

#include "gclient.hpp"

#include "../networkcommon/source/message.hpp"
#include "../networkcommon/source/roommessage.hpp"

gclient::~gclient() {}

void gclient::onconnect(conn_io_client* qconnection) {
	Document doc;
	msg_room_match_request* msg = dynamic_cast<msg_room_match_request*>(msg_room_match_request::create());
	// NOTE :- this pid must be unique and it must be generated by a centralised system.
	// Here we are using the cid hash to generate a unique id for demo purpose.
	msg->pid.format("%lx", qconnection->cid_hash_val);
	qstring msg_room_config_packet;
	msg->serialize(doc, doc.GetAllocator());
	essentials::get_json_string(doc, msg_room_config_packet);
	debug_print(LOG_LEVEL_2, __LOGTAG__, "room config --> %s", msg_room_config_packet.c_str());
	send_message(msg_room_config_packet, true);
	GX_DELETE(msg);
}
