using System;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Text.Json;
using qsdk;
using UnityEngine;

// internal interface IQNetClientLifeCycleCommands
// {
//     void InitLifeCycle();
//     void StartClientConnection();
//     void RequestMatch();
//     int SendMessage(string message, bool flush);
//     int CloseConnection();
//     void LogMessage(string msg);
//     void LogWarning(string msg);
// }
internal interface IQNetClientLifeCycle
{
    void OnInitLifeCycle();
    void OnClientConnect();
    void OnClientReleaseConnection();
    void OnClientCloseConnection();
    void OnRoomPlayerAdd(ulong len, byte[] buf, string msg);
    void OnRoomPlayerRemove(ulong len, byte[] buf, string msg);
    void OnRoomStart(ulong len, byte[] buf, string msg);
    void OnRoomEnd(ulong len, byte[] buf, string msg);
    void OnSpawnFromServer(ulong len, byte[] buf, string msg);
}
public class QNetClientLifeCycle : MonoBehaviour, IQNetClientLifeCycle
{
    public enum  EClientConnectionState
    {
        UnInitialised,
        Started,
        ConnectedToServer,
        Close,
        Released,
        Error
    }
    
    private qunitysdk.qsocket _qsocket = null;
    [SerializeField]
    private string _pid = "123";
    [SerializeField]
    private string _serverIP = "15.206.79.30";
    [SerializeField]
    private EClientConnectionState _connectionState = EClientConnectionState.UnInitialised;
    private MessageHandler _messageHandler = new MessageHandler();
    private Room _managedRoom;
    
    public EClientConnectionState ConnectionState
    {
        get { return _connectionState; }
    }
    
    public string ServerIp
    {
        get { return _serverIP; }
        set { _serverIP = value; }
    }
    
    public string Pid
    {
        get { return _pid; }
        set { _pid = value; }
    }

    public void InitLifeCycle()
    {
#if UNITY_SERVER
        qnetbehaviour.LogWarn($"QNetClientLifeCycle can't be inited on SERVER, ignoring InitLifeCycle  !!!");
        return;
#endif
        if (ConnectionState >= EClientConnectionState.Started)
        {
            qnetbehaviour.LogError($"Invalid State, {ConnectionState}, ignoring InitLifeCycle  !!!");
            return;
        }
        
        if (_qsocket != null)
        {
            qnetbehaviour.LogError("qsocket already created, ignoring InitLifeCycle !!!");
            return;
        }
        
        _qsocket = new qunitysdk.qsocket();
        // register handlers
        _messageHandler.RegisterHandler(msg_room_server_event_player_add.get_type_string_crc(), RoomPlayerAdd);
        _messageHandler.RegisterHandler(msg_room_server_event_player_remove.get_type_string_crc(), OnRoomPlayerRemove);
        _messageHandler.RegisterHandler(msg_room_server_event_start.get_type_string_crc(), OnRoomStart);
        _messageHandler.RegisterHandler(msg_room_server_event_end.get_type_string_crc(), OnRoomEnd);
        _messageHandler.RegisterHandler(rpc_spawn_msg.get_type_string_crc(), SpawnFromServer);
        OnInitLifeCycle();
    }
    
    public void StartClientConnection()
    {
        if (_qsocket == null)
        {
            qnetbehaviour.LogError("qsocket not created !!!");
            return;
        }

        if (!(ConnectionState == EClientConnectionState.UnInitialised || ConnectionState == EClientConnectionState.Released))
        {
            qnetbehaviour.LogError($"Invalid State, {ConnectionState}  !!!");
            return;
        }
        // NOTE :- this pid must be unique and it must be generated by a centralised system.
        // Here we are using the guid hash to generate a unique id for demo purpose.
        _pid = _qsocket.guid_crc.ToString("x");
        LogMessage("guid " + _qsocket.guid_crc);
        
        IntPtr instancePtr = (IntPtr)GCHandle.Alloc(this, GCHandleType.Normal);
        _qsocket.connect(_serverIP, "4000", instancePtr);
        _qsocket.OnConnect = OnConnect;
        _qsocket.OnMessage = OnMessage;
        _qsocket.OnReleaseConnection = OnReleaseConnection;
        _qsocket.OnClose = OnClose;
        SetState(EClientConnectionState.Started);
    }
    
    public void RequestMatch()
    {
        if (_qsocket == null)
        {
            qnetbehaviour.LogError("qsocket not created !!!");
            return;
        }
        if (ConnectionState != EClientConnectionState.ConnectedToServer)
        {
            qnetbehaviour.LogError($"Invalid State, {ConnectionState}  !!!");
            return;
        }
        msg_room_match_request msg_room_config_packet = new msg_room_match_request(_pid);
        msg_room_config_packet.room_config = new msg_room_config();
        string payload = JsonSerializer.Serialize(msg_room_config_packet);
        LogMessage($"Sending match request : {payload}");
        _qsocket.sendMessage(payload, true);
    }

    private void SpawnFromServer(ulong len, byte[] buf, string msg)
    {
        rpc_spawn_msg spawnMsg = JsonSerializer.Deserialize<rpc_spawn_msg>(msg);

        OnSpawnFromServer(len, buf, msg);
    }
    
    protected int SendMessage(string message, bool flush)
    {
        if (_qsocket == null)
        {
            qnetbehaviour.LogError("qsocket not created !!!");
            return -1000;
        }
        if (ConnectionState != EClientConnectionState.ConnectedToServer)
        {
            qnetbehaviour.LogError($"Invalid State, {ConnectionState}  !!!");
            return -1001;
        }
        return _qsocket.sendMessage(message, flush);
    }

    
    protected int CloseConnection()
    {
        if (_qsocket == null)
        {
            qnetbehaviour.LogError("qsocket not created !!!");
            return -1000;
        }
        return _qsocket.close();
    }
    
    private void SetState(EClientConnectionState newConnectionState)
    {
        if (_connectionState != newConnectionState)
        {
            EClientConnectionState previousConnectionState = _connectionState;
            _connectionState = newConnectionState;
            OnStateChange(previousConnectionState);
        }
    }

    public void LogMessage(string msg) {
        qnetbehaviour.LogInfo($"[{typeof(QNetClientLifeCycle)}] - [{_pid}]: {msg}");
    }
    public void LogWarning(string msg) {
        qnetbehaviour.LogWarn($"[{typeof(QNetClientLifeCycle)}] - [{_pid}]: {msg}");
    }
    
    public static object FromIntPtr( IntPtr ptr ) {
        GCHandle handle = GCHandle.FromIntPtr(ptr);
        return handle.Target;
    }

    public static void FreeHandle( IntPtr ptr ) {
        GCHandle handle = GCHandle.FromIntPtr(ptr);
        handle.Free();
    }
    
    private void OnStateChange(EClientConnectionState previousConnectionState)
    {
        LogMessage($"connection state changed {previousConnectionState} --> {_connectionState}");
        switch (_connectionState)
        {
            case EClientConnectionState.Started:
            {
                break;
            }
            case EClientConnectionState.ConnectedToServer:
            {
                OnClientConnect();
                break;
            }
            case EClientConnectionState.Released:
            {
                OnClientReleaseConnection();
                break;
            }
            case EClientConnectionState.Close:
            {
                OnClientCloseConnection();
                break;
            }
        }
    }
    
    private void OnConnect( qunitysdk.qsocket qs, IntPtr userData ) {
        QNetClientLifeCycle thiz = (QNetClientLifeCycle) StatefulClientExample.FromIntPtr(userData);
        LogMessage($"server ip from arg {thiz._serverIP}");
        StatefulClientExample.FreeHandle(userData);
        SetState(EClientConnectionState.ConnectedToServer);
    }
    
    private void OnMessage( qunitysdk.qsocket qs, ulong recv_len, byte[] buffer ) {
        ushort sig;
        ulong t_crc;
        string jsonString;
        JsonDocument doc;
        int result = message_room_base.deserialize_header(recv_len, buffer, out jsonString, out sig, out t_crc, out doc);
        if (result == 0)
        {
            _messageHandler.HandleMessage(t_crc, recv_len, buffer, jsonString);
        }
        doc?.Dispose();
        string msg = System.Text.Encoding.UTF8.GetString(buffer, 0, (int)recv_len);
        LogMessage($"received : {msg}");
    }

    private void OnReleaseConnection( qunitysdk.qsocket qs )
    {
        SetState(EClientConnectionState.Released);
        LogMessage("qsocket release connection");
    }

    private void OnClose( qunitysdk.qsocket qs ) {
        SetState(EClientConnectionState.Close);
        LogMessage("qsocket close connection");
    }

    private void RoomPlayerAdd(ulong len, byte[] buf, string msg)
    {
        msg_room_server_event_player_add playerAddMsg = JsonSerializer.Deserialize<msg_room_server_event_player_add>(msg);

        if (_managedRoom == null)
        {
            _managedRoom = new ClientRoom(playerAddMsg.room_id, this.gameObject);
            LogMessage($"Client room created {_managedRoom.RoomID}");
        }
        else
        {
            if (_managedRoom.RoomID != playerAddMsg.room_id)
            {
                _managedRoom.ReleaseAllMetaInstances();
                _managedRoom = new ClientRoom(playerAddMsg.room_id, this.gameObject);
            }
        }

        foreach (var player in playerAddMsg.players)
        {
            _managedRoom.AddOrUpdatePlayerMeta(player.pid, (ulong)player.hash);
        }
        OnRoomPlayerAdd(len, buf, msg);
    }
    
    // interface functions
    public virtual void OnInitLifeCycle(){}
    public virtual void OnClientConnect(){}
    public virtual void OnClientReleaseConnection(){}
    public virtual void OnClientCloseConnection(){}
    public virtual void OnRoomPlayerAdd(ulong len, byte[] buf, string msg){}
    public virtual void OnRoomPlayerRemove(ulong len, byte[] buf, string msg){}
    public virtual void OnRoomStart(ulong len, byte[] buf, string msg){}
    public virtual void OnRoomEnd(ulong len, byte[] buf, string msg){}
    public virtual void OnSpawnFromServer(ulong len, byte[] buf, string msg){}
}
