name: Generate and Publish Docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx breathe sphinx_rtd_theme sphinx-copybutton  # Add sphinx-copybutton here
        # For testing frameworks
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libgtest-dev

    - name: Install Doxygen
      run: sudo apt-get install -y doxygen
   
       - name: Run tests
      working-directory: qh3client
      run: make test

    - name: Execute qh3client test application
      working-directory: qh3client
      run: |
        ./qh3client-test-app --gtest_output=xml:qh3client-test-results.xml
    - name: Convert Test Results to HTML
      working-directory: qh3client
      run: |
        python3 ./convert_gtest_xml_to_html.py ./qh3client-test-results.xml ./qh3client-test-results.html

    - name: Generate Doxygen documentation
      run: |
        cd docs
        doxygen Doxyfile
   
    - name: Generate Sphinx documentation
      run: |
        cd docs/sphinx/source
        sphinx-build -b html . ./../build/html
    - name: Copy test results to the Sphinx documentation build/html directory
        run: |
          mkdir -p docs/sphinx/build/html/test-results
          cp qh3client/qh3client-test-results.html docs/sphinx/build/html/test-results/qh3client-test-results.html
 
    - name: Checkout the docs repository
      uses: actions/checkout@v2
      with:
        repository: arunmudhaliar/docs
        path: docs_repo
        token: ${{ secrets.DOCS_REPO_TOKEN }}
   
    - name: Copy generated docs to the docs repository
      run: |
        rsync -av --delete docs/sphinx/build/html/ docs_repo/docs/gearsdk-docs/
      
    - name: Commit and push changes
      run: |
        cd docs_repo
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add .
        git commit -m "Update Gearsdk documentation"
        git push
