name: qh3client-test

on:
  push:
    paths:
      - 'qh3client/**'
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libgtest-dev

    - name: Run tests
      working-directory: qh3client
      run: make test

    - name: Execute the test application
      working-directory: qh3client
      run: |
        ./qh3client-test-app --gtest_output=xml:qh3client-test-results.xml
    - name: Convert Test Results to HTML
      working-directory: qh3client
      run: |
        python3 ./convert_gtest_xml_to_html.py ./qh3client-test-results.xml ./qh3client-test-results.html

    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: qh3client-test-results-xml
        path: qh3client/qh3client-test-results.xml

    - name: Upload HTML Test Results
      uses: actions/upload-artifact@v3
      with:
        name: qh3client-test-results-html
        path: qh3client/qh3client-test-results.html
