name: qh3client-test

on:
  push:
    paths:
      - 'qh3client/**'
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libgtest-dev

    - name: Run tests
      working-directory: qh3client
      run: make test

    - name: Execute the tests
      working-directory: qh3client
      run: |
        ./qh3client-test-app